export const INTEGRATION_KEYS = {
  ftp_enabled: "Включено",
  ftp_host: "Host",
  ftp_user: "User",
  ftp_password: "Password",
  ftp_sync_from_date: "Выгружать с даты",
  ftp_exclude_phone_numbers: "Исключить номера",
  megapbx_enabled: "Включено",
  megapbx_base_url: "Base URL",
  megapbx_api_key: "API key",
  megapbx_auth_scheme: "Схема авторизации",
  megapbx_api_key_header: "Заголовок API key",
  megapbx_employees_path: "Путь сотрудников",
  megapbx_employees_result_key: "Ключ результата сотрудников",
  megapbx_numbers_path: "Путь номеров",
  megapbx_numbers_result_key: "Ключ результата номеров",
  megapbx_calls_path: "Путь звонков",
  megapbx_calls_result_key: "Ключ результата звонков",
  megapbx_recordings_path: "Путь записей",
  megapbx_recordings_result_key: "Ключ результата записей",
  megapbx_webhook_path: "Путь вебхука",
  megapbx_webhook_secret: "Секрет вебхука",
  megapbx_ftp_host: "FTP host",
  megapbx_ftp_user: "FTP user",
  megapbx_ftp_password: "FTP password",
  megapbx_sync_employees: "Синхронизировать сотрудников",
  megapbx_sync_numbers: "Синхронизировать номера",
  megapbx_sync_calls: "Синхронизировать звонки",
  megapbx_sync_recordings: "Скачивать записи",
  megapbx_webhooks_enabled: "Включить вебхуки",
  telegram_bot_token: "Token",
  max_bot_token: "Token",
} as const;
